import type { Entry } from "@/types"
import { getLocalDateString } from "@/lib/utils"

// Generate realistic sample reflections anchored to the user's current month/week
export function generateMockEntries(): Entry[] {
  const now = Date.now()
  const DAY_MS = 86400000

  // 14 days of sample reflections leading up to today
  const template = [
    {
      daysAgo: 13,
      timeOfDay: "evening" as const,
      mood: 4,
      energy: 4,
      activityLevel: 3,
      sleepHours: 7.5,
      waterLevel: "2–3L",
      stress: 2,
      note: "Evening walk through the park. Felt calm.",
      activities: ["Walking", "Nature"],
    },
    {
      daysAgo: 12,
      timeOfDay: "morning" as const,
      mood: 3.5,
      energy: 3,
      activityLevel: 2,
      sleepHours: 6.5,
      waterLevel: "1–2L",
      stress: 3,
      note: "A bit groggy waking up, but got some reading done.",
      activities: ["Reading", "Cafe"],
    },
    {
      daysAgo: 11,
      timeOfDay: "evening" as const,
      mood: 4.5,
      energy: 5,
      activityLevel: 4,
      sleepHours: 8,
      waterLevel: "2–3L",
      stress: 1,
      note: "Super productive dev session and gym afterward!",
      activities: ["Development", "Gym", "Exercise"],
    },
    {
      daysAgo: 10,
      timeOfDay: "afternoon" as const,
      mood: 3,
      energy: 3,
      activityLevel: 2,
      sleepHours: 6,
      waterLevel: "1–2L",
      stress: 3,
      note: "Busy workday. Took a quick breather.",
      activities: ["Study"],
    },
    {
      daysAgo: 9,
      timeOfDay: "evening" as const,
      mood: 4,
      energy: 4,
      activityLevel: 3,
      sleepHours: 7.5,
      waterLevel: "2–3L",
      stress: 2,
      note: "Cooked a nice dinner with friends.",
      activities: ["Cooking", "Friends"],
    },
    {
      daysAgo: 8,
      timeOfDay: "morning" as const,
      mood: 4.5,
      energy: 4,
      activityLevel: 3,
      sleepHours: 8.5,
      waterLevel: "3L+",
      stress: 1,
      note: "Slept like a rock. Morning yoga felt so good.",
      activities: ["Yoga", "Reading"],
    },
    {
      daysAgo: 7,
      timeOfDay: "afternoon" as const,
      mood: 3.5,
      energy: 3,
      activityLevel: 3,
      sleepHours: 7,
      waterLevel: "2–3L",
      stress: 2,
      note: "Quiet Sunday afternoon. Watched a classic movie.",
      activities: ["Movie", "Reading"],
    },
    {
      daysAgo: 6,
      timeOfDay: "evening" as const,
      mood: 4,
      energy: 4,
      activityLevel: 4,
      sleepHours: 7.5,
      waterLevel: "2–3L",
      stress: 2,
      note: "Great run around the lake.",
      activities: ["Running", "Exercise"],
    },
    {
      daysAgo: 5,
      timeOfDay: "morning" as const,
      mood: 4.5,
      energy: 5,
      activityLevel: 4,
      sleepHours: 8,
      waterLevel: "3L+",
      stress: 1,
      note: "Woke up energized and solved tough problem.",
      activities: ["Competitive Programming", "Development"],
    },
    {
      daysAgo: 4,
      timeOfDay: "afternoon" as const,
      mood: 3,
      energy: 2.5,
      activityLevel: 2,
      sleepHours: 5.5,
      waterLevel: "1–2L",
      stress: 4,
      note: "Late night yesterday caught up with me.",
      activities: ["Study"],
    },
    {
      daysAgo: 3,
      timeOfDay: "evening" as const,
      mood: 4.5,
      energy: 4,
      activityLevel: 3,
      sleepHours: 8,
      waterLevel: "2–3L",
      stress: 1,
      note: "Caught up on sleep, felt much lighter today.",
      activities: ["Reading", "Nature"],
    },
    {
      daysAgo: 2,
      timeOfDay: "evening" as const,
      mood: 5,
      energy: 5,
      activityLevel: 4,
      sleepHours: 8,
      waterLevel: "3L+",
      stress: 1,
      note: "Celebrated finishing a big milestone!",
      activities: ["Development", "Friends", "Music"],
    },
    {
      daysAgo: 1,
      timeOfDay: "afternoon" as const,
      mood: 4,
      energy: 4,
      activityLevel: 3,
      sleepHours: 7.5,
      waterLevel: "2–3L",
      stress: 2,
      note: "Long walk and coffee at my favorite spot.",
      activities: ["Walking", "Cafe", "Reading"],
    },
    {
      daysAgo: 0,
      timeOfDay: "morning" as const,
      mood: 4.5,
      energy: 4,
      activityLevel: 3,
      sleepHours: 7.5,
      waterLevel: "2–3L",
      stress: 1,
      note: "Ready for a fresh, gentle day.",
      activities: ["Reading", "Exercise"],
    },
  ]

  return template.map((item, idx) => {
    const d = new Date(now - item.daysAgo * DAY_MS)
    return {
      id: `mock-entry-${idx}`,
      date: getLocalDateString(d),
      timeOfDay: item.timeOfDay,
      mood: item.mood,
      energy: item.energy,
      activityLevel: item.activityLevel,
      sleepHours: item.sleepHours,
      waterLevel: item.waterLevel,
      stress: item.stress,
      note: item.note,
      journal: null,
      activities: item.activities,
      loggedAt: d.getTime(),
    }
  })
}
